INSERT INTO `events` (`id`, `name`, `frequency`, `date`, `time`, `description`, `image`, `capacity`, `email`, `phone`, `place`, `street`, `postal_code`, `city`, `country`, `link`, `type`) VALUES (
NULL,
'Campus WU',
'Every Day',
NULL,
NULL,
"Internationally acclaimed architects, including Zaha Hadid, designed the new campus of the Vienna University of Economics and Business. Vienna therefore has not only a new university but also a new destination for people with an interest in architecture.",
'https://www.wien.info/media/images/41161-campus-der-wirtschaftsuniversitaet-1to1.jpeg',
NULL,
NULL,
'+43 1 313 36-0',
'Campus WU',
'Welthandelsplatz 1',
'1020 ',
'Wien',
'Austria',
'www.wu.ac.at',
'Architecture'),

(NULL,
'Vienna Main Library (Hauptbücherei Wien)',
'Every Day',
NULL,
NULL,
"One of the most fascinating facets of the Main Library of the City Libraries is the view through its vast glass facades: Kahlenberg, Leopoldsberg and large parts of the Vienna Woods seem close enough to touch. Spacious library rooms with Internet and audio stations, reading nooks and a café are conducive to reading and reflecting.",
'https://www.wien.info/media/images/hauptbuecherei-aussen-30906-hauptbibliothek-1to1.jpeg',
'5000',
'bib.auskunft@buechereien.wien.at',
'+43 1 4000 84 500',
'Vienna Main Library',
'Urban-Loritz-Platz 2a',
'1070 ',
'Wien',
'Austria',
'www.buechereien.wien.at',
'Education'),

(NULL,
'Danzón - El ritmo latino',
'Every Day',
NULL,
NULL,
"Mediterranean joie de vivre with enough space for the right moves on the dance floor can be found at Danzón in the heart of Vienna. The hips swing to all styles of Latin American music and the accompanying drinks are professionally mixed.",
'https://www.wien.info/media/images/danzon-latin-club-1to1.jpeg',
'5000',
'office@danzon.club',
'+43 676 55 05 840',
'Danzón',
'Johannesgasse 3',
'1010',
'Wien',
'Austria',
'www.danzon.club',
'Club'),

(NULL,
'Danzón - El ritmo latino, Salsa Cubana Intermediate mit Blaga',
'Every Tuesday',
NULL,
'20:30:00',
"Der Salsa Cubana Intermediate Workshop besteht aus 4 Einheiten jeweils á 1 Stunde und findet wöchentlich statt, immer am Donnerstag von 20.30 bis 21.30 Uhr.
Die Teilnehmer sollten Salsa Basiskenntnisse besitzen, d.h. Basic I & II Workshops abgeschlossen haben und die Grundschritte und den Takt gut können. 
Verschiedene kubanische Tanzfiguren werden beigebracht, wobei viele Tipps zum Styling gegeben und typische kubanische Schrittvariationen gezeigt werden.
Nach dem Workshop findet die Salsa Cubana Party statt, die eine tolle Möglichkeit ist, die gelernten Tanzfiguren zu üben und sich mit allen Salseros sozialisieren.",
'https://www.danzon.club/images/blaga.jpg',
'5000',
'office@danzon.club',
'+43 676 55 05 840',
'Danzón',
'Johannesgasse 3',
'1010',
'Wien',
'Austria',
'www.danzon.club',
'Club'),

(NULL,
'Shlomit Butbul',
NULL,
'2019-04-09',
'19:00:00',
"Die junge Dame ist in Israel auf die Welt gekommen, singt in unzähligen Sprachen und läßt sich nur sehr schwer in eine musikalische Kategorie einordnen – ihr Repertoire umfasst Volkslieder der eigenen und fremden Wurzeln, Pop, Folk, Operette, Tagesschlager, Jazz, Blues und eigentlich alles, was ihr gefällt (es könnte also sogar eine Opernarie auftauchen). Shlomit Butbul hat sich für ihr JAZZLAND-Debut zielsicher eine Superband gewünscht: Herwig Gradischnig sax, Oliver Kent b, Hans Strasser b und Christian Salfellner dm.",
'http://www.jazzland.at/prog/bilder/p190409_shlomit_butbul_k.jpg',
'50',
'office@jazzland.at',
'+43 1 533 25 75',
'Jazzland',
'Franz-Josefs-Kai 29',
'1010 ',
'Wien',
'Austria',
'www.jazzland.at',
'Music'),

(NULL,
'Beirut',
NULL,
'2019-04-14',
'20:00:00',
"Endlick kommt Beirut nach Wien mit dabei ihr neues Album Gallipoli, welches Februar 2019 erscheinen wird.
Special Guest ist Helado Negro",
'https://media.npr.org/assets/img/2018/10/19/beirut-press-photo-3b0d4f5551709faee2ad82c27e2a74f51d6aae75-s800-c85.jpg',
'4200',
'office@planet.tt',
'+43 1 332 46 41',
'Gasometer',
'Guglgasse 8',
'1110 ',
'Wien',
'Austria',
'www.planet.tt',
'Music'),

(NULL,
'Verteidigung der Demokratie',
NULL,
'2019-04-18',
'19:30:00',
"Politshow mit Musik
Stück und Regie Christine Eder",
'https://events.wien.info/media/full/VT_ARCHITEKTUR_11_c_Lupi_Spuma.jpg',
'500',
'ticket@volkstheater.at',
'+43 1 52 111 400',
'Volkstheater',
'Arthur-Schnitzler-Platz 1',
'1070 ',
'Wien',
'Austria',
'www.volkstheater.at',
'Politik');